name: Secret Practice

on:
  push:

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
          
          - name: Show Repository Files
           run: ls -la
          - name: show file read
           run: cat README.md
          - name: Check README
           run: test -f README.md
