name: My First GitHub Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from my CI pipeline!"

      - name: Show Files
        run: ls -la

      - name: Show Current Directory
        run: pwd

      - name: Check Runner
        run: |
          echo "I am running on:"
          uname -a
          echo "Operating system:"
          cat /etc/os-release

      - name: Test Success
        run: |
          echo "This test passed"
          exit 0
